version: 2
jobs:
  build:
    working_directory: ~/ionic-native/
    docker:
      - image: node:7
    steps:
      - checkout
      - restore_cache:
         key: ionic-site-{{ .Branch }}
      - run:
         name: Prepare ionic-site repo
         command: |
           if [ "${CIRCLE_BRANCH}" == "master" ]; then
             ./scripts/docs/prepare.sh
           fi
      - save_cache:
         key: ionic-site-{{ .Branch }}
         paths:
         - ~/ionic-site/
      - restore_cache:
         key: node_modules_{{ checksum "package.json" }}
      - run:
         name: Install node modules
         command: npm i
      - save_cache:
         key: node_modules_{{ checksum "package.json" }}
         paths:
         - ~/ionic-native/node_modules/
      - run:
          name: Run tests
          command: npm test
      - run:
          name: Building library
          command: npm run build
      - add_ssh_keys
      - deploy:
          name: Update docs
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              ./scripts/docs/update_docs.sh
            else
              echo "We are on ${CIRCLE_BRANCH} branch, not going to update docs."
            fi
