import { Injectable } from '@angular/core';
import { Plugin, Cordova, AwesomeCordovaNativePlugin } from '@awesome-cordova-plugins/core';

/**
 * @name FirebasexCrashlytics
 * @description
 * Cordova plugin for Firebase Crashlytics - part of the modular cordova-plugin-firebasex family.
 * @usage
 * ```typescript
 * import { FirebasexCrashlytics } from '@awesome-cordova-plugins/firebasex-crashlytics/ngx';
 *
 * constructor(private firebasexCrashlytics: FirebasexCrashlytics) { }
 *
 * ...
 *
 * this.firebasexCrashlytics.logError('Something went wrong');
 * ```
 */
@Plugin({
  pluginName: 'FirebasexCrashlytics',
  plugin: 'cordova-plugin-firebasex-crashlytics',
  pluginRef: 'FirebasexCrashlytics',
  repo: 'https://github.com/dpa99c/cordova-plugin-firebasex-crashlytics',
  platforms: ['Android', 'iOS'],
})
@Injectable()
export class FirebasexCrashlytics extends AwesomeCordovaNativePlugin {
  /**
   * Enable/disable Crashlytics collection.
   *
   * @param {boolean} enabled
   * @returns {Promise<any>}
   */
  @Cordova()
  setCrashlyticsCollectionEnabled(enabled: boolean): Promise<any> {
    return;
  }

  /**
   * Get the current Crashlytics data collection enabled state.
   *
   * @returns {Promise<boolean>}
   */
  @Cordova()
  isCrashlyticsCollectionEnabled(): Promise<boolean> {
    return;
  }

  /**
   * Set a user id for use in Crashlytics crash reports.
   *
   * More info https://firebase.google.com/docs/crashlytics/customize-crash-reports?authuser=0#set_user_ids
   *
   * @param {string} userId
   * @returns {Promise<any>}
   */
  @Cordova()
  setCrashlyticsUserId(userId: string): Promise<any> {
    return;
  }

  /**
   * Set a custom key-value pair for Crashlytics crash reports. Appears in the "Keys" tab of a crash report.
   *
   * @param {string} key
   * @param {string | number | boolean} value
   * @returns {Promise<any>}
   */
  @Cordova()
  setCrashlyticsCustomKey(key: string, value: string | number | boolean): Promise<any> {
    return;
  }

  /**
   * Simulates (causes) a fatal native crash which causes a crash event to be sent to Crashlytics (useful for testing).
   * Crashes will appear under Event type = "Crashes" in the Crashlytics console.
   *
   * @returns {Promise<any>}
   */
  @Cordova()
  sendCrash(): Promise<any> {
    return;
  }

  /**
   * Sends a crash-related log message that will appear in the Logs section of the next native crash event.
   * Note: if you don't then crash, the message won't be sent! Also logs the message to the native device console.
   *
   * @param {string} message
   * @returns {Promise<any>}
   */
  @Cordova()
  logMessage(message: string): Promise<any> {
    return;
  }

  /**
   * Sends a non-fatal error report to Crashlytics, optionally with a stack trace generated by stacktrace.js.
   * The event will appear under Event type = "Non-fatals" in the Crashlytics console.
   * Also logs the error message to the native device console.
   *
   * @param {string} message
   * @param {object} [stackTrace] - a stack trace generated by stacktrace.js
   * @returns {Promise<any>}
   */
  @Cordova()
  logError(message: string, stackTrace?: object): Promise<any> {
    return;
  }

  /**
   * Returns whether the app crashed during the previous execution.
   *
   * @returns {Promise<boolean>}
   */
  @Cordova()
  didCrashOnPreviousExecution(): Promise<boolean> {
    return;
  }
}
